### ISSUE TITLE
Session Tracking

### ISSUE THREAD

**Issue by kamthamc** [svcorg/ReadingStats#5]
* [ ] Start a session (App, Siri, Shortcuts)
* [ ] Track Pages read, time spent
* [ ] Ability to pause session
